public class ExceptionHandlingExample {
    public static void main(String[] args) {
        try {
            int data = 100 / 2;
        } catch (ArithmeticException e) {
            System.out.println("Exception caught: Division by zero!");
        } finally {
            System.out.println("Finally block executed.");
        }
        System.out.println("Rest of the code.");
    }
}
